apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ns-1
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: user
  MYSQL_PASSWORD: password
  MYSQL_DATABASE: quotesdb

# apiVersion: v1
# kind: Secret
# metadata:
#   name: mysql-secret
# type: Opaque
# stringData:
#   MYSQL_ROOT_PASSWORD: root
#   MYSQL_USER: user
#   MYSQL_PASSWORD: password
#   MYSQL_DATABASE: quotesdb
