apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ns-1
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: ns-1
spec:
  selector:
    app: api
  ports:
    - port: 5001
      targetPort: 5001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: ns-1
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: app
  ports:
    - port: 5002
      targetPort: 5002
  type: LoadBalancer

# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql
# spec:
#   selector:
#     app: mysql
#   ports:
#     - port: 3306
#       targetPort: 3306
#   type: ClusterIP
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: api
# spec:
#   selector:
#     app: api
#   ports:
#     - port: 5001
#       targetPort: 5001
#   type: ClusterIP
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: app
#   annotations:
#     service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
# spec:
#   selector:
#     app: app
#   ports:
#     - port: 5002
#       targetPort: 5002
#   type: LoadBalancer
